forge "https://forgeapi.puppetlabs.com"

# Using puppet module install doesn't work well - too many issues like permission denied.
# Use git directly instead
#
#mod "puppetlabs/stdlib", "4.9.0"
#mod "puppetlabs/inifile", "1.4.2"

mod 'puppetlabs-stdlib',
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git",
  :ref => '4.9.0'

mod 'puppetlabs-inifile',
  :git => "git://github.com/puppetlabs/puppetlabs-inifile.git",
  :ref => '1.4.2'